name: 构建可执行程序

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
        
    - name: 合并并编译脚本
      run: |
        # 创建完整的合并文件（包含所有脚本内容）
        {
          echo '#!/bin/bash'
          echo 'SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)'
          
          # 插入cf.sh内容（跳过shebang）
          tail -n +2 cf
          
          # 插入start_ddns.sh内容（跳过shebang）
          echo -e "\n# ===== start_ddns.sh 内容 =====\n"
          tail -n +2 start_ddns.sh
          
          # 插入cf_push.sh内容（跳过shebang）
          echo -e "\n# ===== cf_push.sh 内容 =====\n"
          tail -n +2 cf_push.sh
          
          # 添加调用逻辑
          cat << 'EOF'
case "$1" in
    "start") shift; start_ddns "$@" ;;
    "push") shift; cf_push "$@" ;;
    *) cf_main "$@" ;;
esac
EOF
        } > cf-ddns
        
        # 直接使用合并后的脚本（不编译）
        chmod +x cf-ddns
        
    - name: 打包成品
      run: |
        mkdir -p dist
        cp cf-ddns dist/
        
    - name: 上传构建结果
      uses: actions/upload-artifact@v4
      with:
        name: cf-ddns-bin
        path: dist/
